"""Generate a Markdown postmortem report."""

from datetime import UTC, datetime

from autopsy.parsers.base import LogEvent

VERSION = "0.1.0"


def _duration(start: datetime, end: datetime) -> str:
    delta = end - start
    h, rem = divmod(int(delta.total_seconds()), 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m}m"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


def _fmt(dt: datetime) -> str:
    if dt is None:
        return "N/A"
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def generate(
    events: list[LogEvent],
    anomalies: list[dict],
    services: list[str],
) -> str:
    if not events:
        return "# autopsy\n\nNo events found.\n"

    timestamped = [e for e in events if e.timestamp]
    start = timestamped[0].timestamp if timestamped else None
    end = timestamped[-1].timestamp if timestamped else None

    total = len(events)
    errors = sum(1 for e in events if e.level in {"ERROR", "CRITICAL", "FATAL"})
    warns = sum(1 for e in events if e.level in {"WARN", "WARNING"})
    error_pct = (errors / total * 100) if total else 0

    lines = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        "# 🔬 Incident Postmortem",
        f"> Generated by **autopsy v{VERSION}**  ",
        f"> {datetime.now(tz=UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "---",
        "",
    ]

    # ── Summary ─────────────────────────────────────────────────────────────
    lines += [
        "## 📊 Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Window** | {_fmt(start)} → {_fmt(end)} |",
        f"| **Duration** | {_duration(start, end) if start and end else 'N/A'} |",
        f"| **Services analyzed** | {', '.join(sorted(services))} |",
        f"| **Total events** | {total:,} |",
        f"| **Errors** | {errors:,} ({error_pct:.1f}%) |",
        f"| **Warnings** | {warns:,} |",
        f"| **Anomalies detected** | {len(anomalies)} |",
        "",
        "---",
        "",
    ]

    # ── Anomalies ────────────────────────────────────────────────────────────
    if anomalies:
        lines += ["## 🚨 Anomalies Detected", ""]
        for i, a in enumerate(anomalies, 1):
            severity_icon = {"CRITICAL": "🔴", "ERROR": "🟠", "WARNING": "🟡"}.get(
                a["severity"], "🔵"
            )
            lines += [
                f"### {i}. {severity_icon} {a['title']}",
                f"- **Time:** {_fmt(a['timestamp'])}",
                f"- **Severity:** {a['severity']}",
                f"- **Detail:** {a['detail']}",
                "",
            ]
        lines += ["---", ""]

    # ── Timeline ─────────────────────────────────────────────────────────────
    lines += [
        "## 🕐 Event Timeline",
        "",
        "| Time (UTC) | Service | Level | Message |",
        "|-----------|---------|-------|---------|",
    ]

    # Show up to 100 most important events (errors/warns first, then sample)
    important = [
        e for e in timestamped if e.level in {"ERROR", "CRITICAL", "FATAL", "WARN", "WARNING"}
    ]
    important_set = set(id(e) for e in important)
    others = [e for e in timestamped if id(e) not in important_set]

    shown = important[:80]
    # fill remaining slots with regular events evenly spaced
    if len(shown) < 100 and others:
        step = max(1, len(others) // (100 - len(shown)))
        shown += others[::step]

    shown.sort(key=lambda e: e.timestamp)

    for e in shown[:100]:
        msg = e.message.replace("|", "\\|")[:120]
        ts = e.timestamp.strftime("%H:%M:%S") if e.timestamp else "?"
        lines.append(f"| {ts} | {e.service} | {e.level} | {msg} |")

    if total > 100:
        lines.append(f"\n> *Showing key events. {total:,} total events analyzed.*")

    lines += ["", "---", ""]

    # ── Action Items ──────────────────────────────────────────────────────────
    lines += [
        "## ✅ Action Items",
        "",
        "- [ ] Identify root cause",
        "- [ ] Add monitoring/alerting for recurrence",
        "- [ ] Update runbook",
        "- [ ] Share postmortem with team",
        "",
        "---",
        "",
        "*Generated with [autopsy](https://github.com/yourusername/autopsy) — "
        "the CLI that turns logs into postmortems.*",
    ]

    return "\n".join(lines)
